### ISSUE TITLE
Feature grid proposal

### ISSUE THREAD

**Issue by stubailo** [apollostack/dev-home.apollodata.com#1]
I consulted with @zhangela, and she had some really great feedback about the feature grid at the top. Her point was, we should focus on answering the questions people have when they show up to our website, and letting people know about the most important stuff. For example:

1. Fully featured: Queries, caching, mutations, optimistic UI, subscriptions, pagination, server-side rendering, prefetching, and more.
2. Compatible: Supports every GraphQL server and 100% of the specification.
3. Compare to other clients: Something about Relay?
4. Production-ready: Used in critical production apps today by Meteor, NewSpring Church, and others.
5. Community: Over 100 contributors and counting. Built by the community, for the community.
6. Tooling-friendly: Works with all Redux tools, GraphQL editor plugins, and production services.

Features are just one small part of what makes Apollo great, and we should make sure people get the whole story right away.

cc @helfer @tmeasday thoughts?

**Comment by stubailo** [comment]
CC @theadactyl as well

**Comment by tmeasday** [comment]
<strike> More flexible than Relay</strike> -> Flexible ?

**Comment by tmeasday** [comment]
I think add prefetching to the feature list also? Maybe not a big deal.

**Comment by stubailo** [comment]
She was saying it's 100% certain that someone arriving at our front page will be thinking "Why would I use this instead of Relay?" and even though we probably don't want to go too in depth about small tradeoffs, I think it makes sense to call it out by name. Perhaps that's not the right way to do it.

Will add prefetching.

**Comment by stubailo** [comment]
By "she way saying", I mean - I also agree, it seems logical that people would be wondering about that.

**Comment by stubailo** [comment]
We could instead just have a heading "compare to other clients" and just link to our detailed comparison.

**Comment by tmeasday** [comment]
I agree, but OTOH, I feel like I would find it weird to find one library mentioning another in frontline marketing material like this. It feels aggressively competitive, don't you think.

**Comment by tmeasday** [comment]
For example: https://lodash.com -> no mention of "underscore"

**Comment by stubailo** [comment]
I guess it depends on how we frame it - I don't think having the name on there is necessarily aggressive. Perhaps just having a link to a general comparison page is enough, people will know to go there if they have that question?

**Comment by tmeasday** [comment]
Maybe the right balance is to have "Flexible" as the heading but mention Relay in the text and point to the more subtle comparison. Maybe something like:

> *Flexible*
> Use any schema, build tooling or UI layer; works where Relay doesn't (read more).

**Comment by stubailo** [comment]
That still seems a bit aggressive, if that's a concern. Maybe "Unlike Relay, doesn't make any assumptions about your architecture."

**Comment by stubailo** [comment]
Doesn't make any assumptions about your architecture, unlike other clients such as Relay or Cashay.

**Comment by tmeasday** [comment]
Oh, sorry. Yes, I agree it makes more sense to me.

**Comment by stubailo** [comment]
OK now we can go back to bikeshedding each section :]

**Comment by stubailo** [comment]
Updated the home page to match this setup: http://dev-home.apollodata.com/

Please give more feedback!

**Comment by helfer** [comment]
This is great! But to continue bikeshedding:

1. "Doesn't make any assumptions about your architecture" should be changed to "Doesn't force you to use a specific architecture" or something like that.
2. I also wouldn't mention specific other clients on the frontpage. Just say "other clients" and drop the "like ...". If people really want to know they'll follow the link.

**Comment by stubailo** [comment]
This is now implemented, feel free to make changes directly.

**Comment by zol** [comment]
Just found this issue so I'll do some more bike-shedding here even though it's closed. Calling Relay out by name came across to me as somewhat insecure. Also the way we call it out has an aggressive tone (using the word 'force'). I would call out the positive inverse and let people click through to the comparison page. For example, "Incrementally adoptable so you can get started right away. [Compare Apollo to other clients]".

Also, are people attached to the list of co's we call out as production users? I think we could use CreditKarma and Legacy.com instead.

**Comment by stubailo** [comment]
@zol feel free to make those directly, they sound like good changes!
